// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddImageWatermark(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddImageWatermark'](arg1, arg2, arg3);
}

export function AddTextWatermark(arg1, arg2) {
  return window['go']['main']['App']['AddTextWatermark'](arg1, arg2);
}

export function GetImagePreview(arg1) {
  return window['go']['main']['App']['GetImagePreview'](arg1);
}

export function GetSupportedFormats() {
  return window['go']['main']['App']['GetSupportedFormats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}
